server:
  port: 8080

spring:
  application:
    name: dailyquiz2

  devtools:
    restart:
      enabled: true # ?? ??? ???

  thymeleaf:
    cache: false # ??? ???? ?? -> ?? ? ?? ???
    prefix: classpath:/templates/ # ??? ?? ??
    suffix: .html # ??? ?? ???
    mode: HTML # HTML5 ??
    encoding: UTF-8 # ??? ??